name: WebConsole
main: com.mesacarlos.webconsole.WebConsole
api-version: 1.13
version: 1.5
description: WebSockets-based web console
author: Carlos Mesa
commands:
  WebConsole:
    description: Shows version and active connections of WebConsole
    permission: webconsole.webconsole
    usage: /WebConsole