name: WebConsole
main: com.mesacarlos.webconsole.WebConsole
version: 1.3
description: WebSockets-based web console
author: Carlos Mesa
commands:
  WebConsole:
    description: Shows version and active connections of WebConsole
    permission: webconsole.webconsole
    usage: /WebConsole